# -*- coding: utf-8 -*-
"""PyTorch-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fBTY0r3ZfuOTxK-aSw_opZ21XD8yKsZK
"""

!pip3 install torch torchvision torchaudio

import torch

t1 = torch.tensor(4.)

t1

t2 = torch.tensor([[5.,6],[7,8],[9,10]])

t2

t3 = torch.tensor([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

t3

t4 = torch.tensor([1,2,3,4.])

t4

t4.shape, t3.shape, t2.shape, t1.shape

# Create tensors
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)

y = w*x + b

y

y.backward()

# Display gradients
print('dy/dx:',x.grad)
print('dy/dw:',w.grad)
print('dy/db:',b.grad)

import numpy as np
x = np.array([[1,2],[3.,4.]])
x

# Convert numpy array to tensor
y = torch.from_numpy(x)
y

x.dtype, y.dtype

# Convert torch tensor to numpy array
z = y.numpy()
z

