# -*- coding: utf-8 -*-
"""Chess.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lfmX7l5Iw-W7H9UszOrjZjNoCkpbIrkH
"""

!pip install chess

import chess

board = chess.Board()

board.legal_moves

chess.Move.from_uci("a8a1") in board.legal_moves

board.push_san("e4")

board

board.push_san("e5")

board.push_san("Qh5")

board.push_san("Nc6")

board.push_san("Bc4")

board.push_san("a6")

board.push_san("Qxf7")

board.is_checkmate()

board

board = chess.Board("r1bqkb1r/pppp1Qpp/2n2n2/4p3/2B1P3/8/PPPP1PPP/RNB1K1NR b KQkq - 0 4")

board.is_stalemate()

board.outcome()

import chess.svg

chess.svg.piece(chess.Piece.from_symbol("R"))

board = chess.Board("8/8/8/8/4N3/8/8/8 w - - 0 1")

board









